[tools]
node = "lts"
bun = "latest"
go = "latest"
rust = "latest"
deno = "latest"
lua = "5.1"
python = "3"
uv = "latest"
docker-cli = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@readwise/cli" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@tanstack/cli" = "latest"

[settings]
lockfile = true
