[tools]
node = "lts"
bun = "latest"
go = "latest"
rust = "latest"
deno = "latest"
lua = "5.1"
uv = "latest"
docker-cli = "latest"
bob = "latest"
stylua = "latest"
shellcheck = "latest"
shfmt = "latest"
golangci-lint = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ripgrep = "latest"
yazi = "latest"
zoxide = "latest"
delta = "latest"
gum = "latest"
jq = "latest"
yq = "latest"
lazygit = "latest"
atuin = "latest"
gh = "latest"
git-lfs = "latest"
tmux = "latest"
tree-sitter = "latest"
yt-dlp = "latest"
"pipx:gallery-dl" = "latest"
"pipx:eyeD3" = "latest"
opencode = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@readwise/cli" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@tanstack/cli" = "latest"
prettier = "latest"

[settings]
lockfile = true
