# https://docs.aviator.co/aviator-cli/configuration

pullRequest:
  # If true, always open PRs as a draft.
  # If false, PRs will be opened as ready-for-review unless the --draft flag
  # is specified on commands that create pull requests.
  draft: true

  # If true, pull requests will be temporarily transitioned to draft state
  # while being rebased. This avoids accidentally adding unnecessary reviewers
  # to a pull request due to a CODEOWNERS file while the pull request is in a
  # transient state. This only applies when a pull request's base branch is
  # changing.
  # If not specified in the config, the default value is true if there is a
  # CODEOWNERS file present and false otherwise.
  rebaseWithDraft: false

  # If true, open a web browser to the pull request page whenever a pull
  # request is created for the first time.
  openBrowser: true

  # By default, when the pull request title contains "WIP", it automatically sets
  # the PR as a draft PR. Setting this to true suppresses this behavior.
  noWipDetection: false

  # Branch prefix to use for creating new branches.
  # branchNamePrefix: "alice/"

  # If true, the CLI will automatically add/update a comment to all PRs linking
  # other PRs in the stack. False by default.
  writeStack: true

# The remote name. By default av CLI uses "origin".
remote: "origin"
