[layouts.default]
focus = "Agents"

[layouts.default.tabs.Agents]
order = 1
root = { pane = "Agent I" }
splits = [
  { source = "Agent I", pane = "Agent II", direction = "right", ratio = 0.5 },
]

[layouts.default.tabs.Edit]
order = 2
root = { pane = "Nvim" }
splits = []

[layouts.default.tabs.Shells]
order = 3
root = { pane = "Shell I" }
splits = [
  { source = "Shell I", direction = "right", ratio = 0.50, pane = "Shell II" },
  { source = "Shell I", direction = "down", ratio = 0.50, pane = "Shell III" },
  { source = "Shell II", direction = "down", ratio = 0.50, pane = "Shell IV" },
]
