[layouts.default]
focus = "Work"

[layouts.default.tabs.Work]
order = 1
root = { pane = "Agent" }
splits = [
  { source = "Agent", direction = "right", ratio = 0.25, pane = "Nvim", run = "nvim", focus = true },
  # { source = "Agent", direction = "down", ratio = 0.65, pane = "Shell I" },
  { source = "Nvim", direction = "down", ratio = 0.80, pane = "Shell" },
]

[layouts.default.tabs.Servers]
order = 2
root = { pane = "Server I" }
splits = [
  { source = "Server I", direction = "right", ratio = 0.50, pane = "Server II" },
  { source = "Server I", direction = "down", ratio = 0.50, pane = "Server III" },
  { source = "Server II", direction = "down", ratio = 0.50, pane = "Server IV" },
]
