bookmarks:
    - path: /Users/brunner/repos/nikbrunner/dots
    - path: /Users/brunner/repos/nikbrunner/notes
    - path: /Users/brunner/repos/nikbrunner/imf-notes
    - path: /Users/brunner/repos/imfusion/web-ui-poc
    - path: /Users/brunner/repos/black-atom-industries/core
    - path: /Users/brunner/repos/black-atom-industries/helm
