# yaml-language-server: $schema=https://raw.githubusercontent.com/black-atom-industries/helm/main/schema.json

appearance: dark
enable_layouts: false
layout: dev
layout_dir: ~/.config/tmux/layouts
claude_status_enabled: true
git_status_enabled: true
project_dirs:
  - ~/repos
default_session_dir: ~/repos
lazygit_popup:
  width: 100%
  height: 90%
dirty_walkthrough_command: "lazygit -p {}"
ensure_cloned:
  - git@github.com:nikbrunner/dots
  - git@github.com:nikbrunner/notes
  - git@github.com:nikbrunner/the-black-atom
  - git@github.com:nikbrunner/koyo
  - git@github.com:nikbrunner/nbr.haus
  - git@github.com:nikbrunner/fff-snacks.nvim
  - git@github.com:nikbrunner/review.nvim
  - git@github.com:nikbrunner/wallpapers
  - url: git@github.com:black-atom-industries/helm
    post_clone: make install
  - url: git@github.com:black-atom-industries/shiplog
    post_clone: deno task install
  - url: git@github.com:nikbrunner/bm
    post_clone: make install
  - url: git@github.com:nikbrunner/tmux-file-picker
    post_clone: make install
  - git@github.com:black-atom-industries/*
  - url: git@github.com:nikbrunner/fonts
    post_clone: ./install.sh
